server:
  port: 9296

spring:
  application:
    name: config-service



  cloud:
    config:
      server:
        git:
          uri: https://github.com/HyounesH/config-server
          clone-on-start: true


